create table rank
(
    id        int8 generated by default as identity,
    created   timestamp without time zone,
    updated   timestamp without time zone,
    status    varchar(30) not null,
    rank_name varchar(50),
    primary key (id)
);

create table post
(
    id        int8 generated by default as identity,
    created   timestamp without time zone,
    updated   timestamp without time zone,
    status    varchar(30) not null,
    post_name varchar(50),
    primary key (id)
);

create table employee
(
    id              int8 generated by default as identity,
    created         timestamp without time zone,
    updated         timestamp without time zone,
    status          varchar(30) not null,
    surname         varchar(50),
    firstname       varchar(50),
    middle_name     varchar(50),
    birthday        timestamp without time zone,
    personal_number varchar(15),
    rank_id         int8,
    post_id         int8,
    primary key (id)
);

alter table if exists rank
    add constraint uk_rank_name unique (rank_name);

alter table if exists post
    add constraint uk_post_name unique (post_name);

alter table if exists employee
    add constraint uk_personal_number unique (personal_number);

alter table if exists employee
    add constraint fk_employee_rank_id foreign key (rank_id) references rank;

alter table if exists employee
    add constraint fk_employee_post_id foreign key (post_id) references post;